# Criando uma conta de serviço para o usuário com acesso total ao cluster.
# Atenção: Está ação não é uma boa prática para um cluster em produção, ela facilita bastante
# o gerenciamente do cluster em um ambiente de desenvolvimento.
# Autenticação no Kubernetes: https://kubernetes.io/docs/reference/access-authn-authz/rbac/.

apiVersion: v1
kind: ServiceAccount
metadata:
 name: logistica-admin
 namespace: kubernetes-dashboard
---
#Associando a conta com um papel dentro do cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logistica-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  #permitindo acesso total ao cluster
  kind: ClusterRole
  name: cluster-admin
#definindo o usuário que terá acesso total
subjects:
 - kind: ServiceAccount
   name: logistica-admin
   namespace: kubernetes-dashboard
   
