version: "4.15.0"
services:
 mysql:
   image: mysql:8.0.31
   ports:
     - "3306:3306"
   environment:
     MYSQL_DATABASE: algalog
     MYSQL_ROOT_PASSWORD: root

 logistica:
   image: logistica/logistica-api
   ports:
     - "8080:8080"
   environment:
     MYSQL_URL: "jdbc:mysql://mysql:3306/algalog?createDatabaseIfNotExist=true&serverTimezone=UTC"
     MYSQL_USER: root
     MYSQL_PASSWORD: root
   depends_on:
     - mysql